### ISSUE TITLE
Hourly tab: unable to set 0 hour

### ISSUE THREAD

**Issue by davidcaldas** [sojinantony01/react-cron-generator#60]
Hello!

When we enter in the Hourly tab the hour value is 0 and the result expression is "0 0 0/1 1/1 * ? *".

If we change the hour time e trying go back to 0 is not possible, the input only allow an empty value but the expression value is "0 0/1 1/1 * ? *".

As we can see they are different:
"0 0 0/1 1/1 * ? *"
"0 0/1 1/1 * ? *"

Best Regards, David

**Comment by sojinantony01** [comment]
Hi David
Thanks for reporting the issue. I will try to fix ASAP

**Comment by sojinantony01** [comment]
Hi from the above steps, i can understand you are trying to create a cron with zero hour and certain minutes. 
like 0 hour 15 minutes, for this kind of selection you can to select minute tab instead of hourly tab. 

Regarding the value difference, an empty hourly value is getting added to cron expression and cron consider it as a 6 value cron expression.

**Comment by davidcaldas** [comment]
Hello @sojinantony01 !

Sorry, but I make a mistake in the description of the error. The problem I describe is in the minutes input:
(label is on right of the input)
![image](https://github.com/sojinantony01/react-cron-generator/assets/39414148/ec339dbd-93e9-419e-9b2c-5847aa3f3b86)

Best Regards, David
